version: '3.9'

services:
  swagger-go:
    container_name: ${SWAGGER_CONTAINER_NAME}
    build:
      context: ./docs/swagger
    tty: true
    stdin_open: true
    volumes:
      - ./docs/swagger:/app
    ports:
      - ${SWAGGER_PORT}:${SWAGGER_CONTAINER_PORT}
    security_opt:
      - seccomp:unconfined